### ISSUE TITLE
TypeError: Cannot read properties of null (reading '_id')

### ISSUE THREAD

**Issue by yahyo7** [burakorkmez/twitter-clone#3]
I am getting below error after I run build and start the server. web running and after  I sign up/or sign in, I am getting black page with below error: 
TypeError: Cannot read properties of null (reading '_id')
    at dg (index-CFb0_dR-.js:243:7512)
    at Ba (index-CFb0_dR-.js:38:16961)
    at sh (index-CFb0_dR-.js:40:43789)
    at rh (index-CFb0_dR-.js:40:39575)
    at o0 (index-CFb0_dR-.js:40:39503)
    at Vi (index-CFb0_dR-.js:40:39357)
    at Ho (index-CFb0_dR-.js:40:35753)
    at gc (index-CFb0_dR-.js:40:36554)
    at cn (index-CFb0_dR-.js:38:3258)
    at index-CFb0_dR-.js:40:34095

**Comment by yahyo7** [comment]
solved: 
missed some ? when defining user(?).smth

**Comment by suraj-khot-19** [comment]
Always use ? Before using any of the field from user like =>
user?._id
